version: "3.9"

services:
  # https://github.com/FlorianLeChat/Assignment-Manager/tree/master/client
  angular:
    image: assignmentmanager
    container_name: website-front
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 4200:4200

  # https://github.com/FlorianLeChat/Assignment-Manager/tree/master/server
  node:
    image: assignmentapi
    container_name: website-back
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 8010:8010